{
 "title": "Fraud Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Fraud by Category",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "fraud",
     "rawSql": "SELECT COUNT(*), rule FROM alerts         \nWHERE alert_time BETWEEN $__timeFrom() AND $__timeTo()  \nGROUP BY rule"
    }
   ]
  },
  {
   "title": "Last Alerts",
   "type": "table",
   "gridPos": { "h": 20, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "dataset": "fraud",
     "rawSql": "SELECT card_hash, rule, details FROM alerts WHERE $__timeFilter(alert_time) ORDER BY alert_time LIMIT 50 "
    }
   ]
  },
  {
   "title": "Alerts over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "dataset": "fraud",
     "rawSql": "SELECT \n  COUNT(*) AS Total,\n  date_trunc('minute', alert_time) AS alert_time\nFROM alerts\nWHERE alert_time BETWEEN $__timeFrom() AND $__timeTo()\nGROUP BY date_trunc('minute', alert_time)\nORDER BY alert_time"
    }
   ]
  }
 ]
}